name: pull request

on:
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: dotnet build ./src --configuration Release
      - name: Test
        run: dotnet test ./src --configuration Release --no-build